name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: package.json - 1
          env:
            BRANCH: ${{GITHUB_REF}}
          run: echo ${BRANCH}
      - name: package.json - 2
          env:
            BRANCH: ${{GITHUB_REF}}
          run: echo "${BRANCH}"
      - name: package.json - 3
          env:
            BRANCH: ${{GITHUB_REF}}
          run: echo ${BRANCH##*/}
      - name: package.json - 4
          id: branch
          env:
            BRANCH: ${{GITHUB_REF}}
          run: echo ::set-output name=branch::${BRANCH##*/}
          outputs:
            branch: # id of output
              description: 'The time we greeted you'
      - name: package.json - 5
          run: echo ${{ steps.branch.branch}}
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        run: echo "$MATRIX_CONTEXT"
